name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: si12-ship-it
          outputs: outputs: |
  dist/snake.svg
  dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%23f78fb3&color_dots=%23f8a5c2,%23fbcfe8,%23f9a8d4,%23f472b6,%23ec4899
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - uses: actions/deploy-pages@v4
